# Generated by Django 5.0.4 on 2024-05-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairytale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='unread',
            field=models.ManyToManyField(related_name='unread_by', to='fairytale.story'),
        ),
    ]
